CREATE TABLE `school` (
 `schId` int(255) NOT NULL AUTO_INCREMENT,
 `schName` varchar(255) DEFAULT NULL,
 `schCanteenName` varchar(255) DEFAULT NULL,
 `schDepart` varchar(255) DEFAULT NULL,
 `schStudentNum` varchar(255) DEFAULT NULL,
 `schAddress` varchar(255) DEFAULT NULL,
 `schtClient` varchar(255) DEFAULT NULL,
 `schChef` varchar(255) DEFAULT NULL,
 `schPeople` varchar(255) DEFAULT NULL,
 `schNameSurvey` varchar(255) DEFAULT NULL,
 `schSurveyDate` varchar(255) DEFAULT NULL,
 `schTain` varchar(255) DEFAULT NULL,
 `schService` varchar(255) DEFAULT NULL,
 `schLuch` varchar(255) DEFAULT NULL,
 `schSurvey` varchar(255) DEFAULT NULL,
 `schDistric` varchar(255) DEFAULT NULL,
 `schProvince` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`schId`)
) ENGINE=InnoDB AUTO_INCREMENT=110 DEFAULT CHARSET=utf8



CREATE TABLE `schtest` (
 `idschtest` int(255) NOT NULL AUTO_INCREMENT,
 `ex1` varchar(255) DEFAULT NULL,
 `ex2` varchar(255) DEFAULT NULL,
 `ex3` varchar(255) DEFAULT NULL,
 `ex4` varchar(255) DEFAULT NULL,
 `ex5` varchar(255) DEFAULT NULL,
 `ex6` varchar(255) DEFAULT NULL,
 `ex7` varchar(255) DEFAULT NULL,
 `ex8` varchar(255) DEFAULT NULL,
 `ex9` varchar(255) DEFAULT NULL,
 `ex10` varchar(255) DEFAULT NULL,
 `ex11` varchar(255) DEFAULT NULL,
 `ex12` varchar(255) DEFAULT NULL,
 `ex13` varchar(255) DEFAULT NULL,
 `ex14` varchar(255) DEFAULT NULL,
 `ex15` varchar(255) DEFAULT NULL,
 `ex16` varchar(255) DEFAULT NULL,
 `ex17` varchar(255) DEFAULT NULL,
 `ex18` varchar(255) DEFAULT NULL,
 `ex19` varchar(255) DEFAULT NULL,
 `ex20` varchar(255) DEFAULT NULL,
 `ex21` varchar(255) DEFAULT NULL,
 `ex22` varchar(255) DEFAULT NULL,
 `ex23` varchar(255) DEFAULT NULL,
 `ex24` varchar(255) DEFAULT NULL,
 `ex25` varchar(255) DEFAULT NULL,
 `ex26` varchar(255) DEFAULT NULL,
 `ex27` varchar(255) DEFAULT NULL,
 `ex28` varchar(255) DEFAULT NULL,
 `ex29` varchar(255) DEFAULT NULL,
 `ex30` varchar(255) DEFAULT NULL,
 `com1` varchar(45) DEFAULT NULL,
 `com2` varchar(45) DEFAULT NULL,
 `com3` varchar(45) DEFAULT NULL,
 `com4` varchar(45) DEFAULT NULL,
 `com5` varchar(45) DEFAULT NULL,
 `com6` varchar(45) DEFAULT NULL,
 `com7` varchar(45) DEFAULT NULL,
 `com8` varchar(45) DEFAULT NULL,
 `com9` varchar(45) DEFAULT NULL,
 `com10` varchar(45) DEFAULT NULL,
 `com11` varchar(45) DEFAULT NULL,
 `com12` varchar(45) DEFAULT NULL,
 `com13` varchar(45) DEFAULT NULL,
 `com14` varchar(45) DEFAULT NULL,
 `com15` varchar(45) DEFAULT NULL,
 `com16` varchar(45) DEFAULT NULL,
 `com17` varchar(45) DEFAULT NULL,
 `com18` varchar(45) DEFAULT NULL,
 `com19` varchar(45) DEFAULT NULL,
 `com20` varchar(45) DEFAULT NULL,
 `com21` varchar(45) DEFAULT NULL,
 `com22` varchar(45) DEFAULT NULL,
 `com23` varchar(45) DEFAULT NULL,
 `com24` varchar(45) DEFAULT NULL,
 `com25` varchar(45) DEFAULT NULL,
 `com26` varchar(45) DEFAULT NULL,
 `com27` varchar(45) DEFAULT NULL,
 `com28` varchar(45) DEFAULT NULL,
 `com29` varchar(45) DEFAULT NULL,
 `com30` varchar(45) DEFAULT NULL,
 `school_schId` int(255) NOT NULL,
 `img1` longblob,
 `img2` longblob,
 `img3` longblob,
 `img4` longblob,
 PRIMARY KEY (`idschtest`),
 KEY `fk_schtest_school1_idx` (`school_schId`),
 CONSTRAINT `fk_schtest_school1` FOREIGN KEY (`school_schId`) REFERENCES `school` (`schId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8
